#!/usr/bin/env python3

# Copyright (c) 2025 gh-nate
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import argparse
import os
import shutil
import sys
import tempfile

i = int
p = argparse.ArgumentParser()
p.add_argument("src")
p.add_argument("start", type=i)
p.add_argument("end", type=i)
p.add_argument("dst")
p.add_argument("offset", type=i)
args = p.parse_args()

illegal = 0
start = 1

if args.start == illegal:
    sys.exit(f"start counts from {start}")

if args.offset == illegal:
    sys.exit(f"offset counts from {start}")

if args.end == illegal:
    args.end = args.start

if args.start > args.end:
    sys.exit("start > end")

t = tempfile.NamedTemporaryFile("w+t", delete=False)

try:
    with open(args.dst) as f:
        append = True
        for index, f_line in enumerate(f, start):
            if index == args.offset:
                append = False
                break
            t.write(f_line)

        with open(args.src) as o:
            for index, o_line in enumerate(o, start):
                if index >= args.start:
                    t.write(o_line)
                if index == args.end:
                    break

        if not append:
            t.write(f_line)

            for f_line in f:
                t.write(f_line)
except Exception as e:
    t.close()
    os.remove(t.name)
    raise e

t.close()
shutil.move(t.name, args.dst)
